### ISSUE TITLE
Got  Task :checkPython FAILED

### ISSUE THREAD

**Issue by svrprasit12** [xvik/gradle-use-python-plugin#13] opened 2020-10-15 04:33 UTC
I've got  Task :checkPython FAILED 
python/bin/python -c exec("import sys;ver=sys.version_info;print(str(ver.major)+'.'+str(ver.minor)+'.'+str(ver.micro));print(sys.prefix);print(sys.executable)")
when using java 11 and python 3.5
cuz I use docker hub openkbs/jdk11-mvn-py3 to do the gradle build.
I set python env at folder inside project dir call "python"

**Comment by xvik** [comment] 2020-10-16 00:04
Please post the exact error message here (run with `--stacktrace` gradle option) because it should contain an actual python error. 
Also, please show your initial docker command (how you run gradle) so I could easily reproduce your case.

This docker image comes with gradle 4.1 (pretty old) so you must be using an old plugin version (like 1.2.1). Is it correct?

**Comment by xvik** [comment] 2021-03-01 17:17
Most likely fixed in the new release [2.3.0](https://github.com/xvik/gradle-use-python-plugin/releases/tag/2.3.0)

**Closed by xvik** 2021-03-01 17:17 UTC
